{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-19324",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/xmidt-org\/cjwt\/commit\/9304d3e94242c1a6df77b21bde0e949392e1040a",
                    "name": "https:\/\/github.com\/xmidt-org\/cjwt\/commit\/9304d3e94242c1a6df77b21bde0e949392e1040a",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/xmidt-org\/cjwt\/pull\/29#issuecomment-558356866",
                    "name": "https:\/\/github.com\/xmidt-org\/cjwt\/pull\/29#issuecomment-558356866",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "Xmidt cjwt through 1.0.1 before 2019-11-25 maps unsupported algorithms to alg=none, which sometimes leads to untrusted accidental JWT acceptance."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-03-20T18:15Z",
    "lastModifiedDate": "2020-03-20T18:27Z"
}