{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2015-5216",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "http:\/\/www.openwall.com\/lists\/oss-security\/2015\/10\/27\/8",
                    "name": "http:\/\/www.openwall.com\/lists\/oss-security\/2015\/10\/27\/8",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=1255170",
                    "name": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=1255170",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/pagure.io\/ipsilon\/a503aa9c2a30a74e709d1c88099befd50fb2eb16",
                    "name": "https:\/\/pagure.io\/ipsilon\/a503aa9c2a30a74e709d1c88099befd50fb2eb16",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "The Identity Provider (IdP) server in Ipsilon 0.1.0 before 1.0.1 does not properly escape certain characters in a Python exception-message template, which makes it easier for remote attackers to conduct cross-site scripting (XSS) attacks via an HTTP response."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-02-17T19:15Z",
    "lastModifiedDate": "2020-02-17T19:15Z"
}