{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-5390",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/IdentityPython\/pysaml2\/commit\/5e9d5acbcd8ae45c4e736ac521fd2df5b1c62e25",
                    "name": "https:\/\/github.com\/IdentityPython\/pysaml2\/commit\/5e9d5acbcd8ae45c4e736ac521fd2df5b1c62e25",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/IdentityPython\/pysaml2\/commit\/f27c7e7a7010f83380566a219fd6a290a00f2b6e",
                    "name": "https:\/\/github.com\/IdentityPython\/pysaml2\/commit\/f27c7e7a7010f83380566a219fd6a290a00f2b6e",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/IdentityPython\/pysaml2\/releases",
                    "name": "https:\/\/github.com\/IdentityPython\/pysaml2\/releases",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/IdentityPython\/pysaml2\/releases\/tag\/v5.0.0",
                    "name": "https:\/\/github.com\/IdentityPython\/pysaml2\/releases\/tag\/v5.0.0",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/pypi.org\/project\/pysaml2\/5.0.0\/",
                    "name": "https:\/\/pypi.org\/project\/pysaml2\/5.0.0\/",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "PySAML2 before 5.0.0 does not check that the signature in a SAML document is enveloped and thus signature wrapping is effective, i.e., it is affected by XML Signature Wrapping (XSW). The signature information and the node\/object that is signed can be in different places and thus the signature verification will succeed, but the wrong data will be used. This specifically affects the verification of assertion that have been signed."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-01-13T19:15Z",
    "lastModifiedDate": "2020-01-13T19:47Z"
}