{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-4205",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/exchange.xforce.ibmcloud.com\/vulnerabilities\/174961",
                    "name": "ibm-datapower-cve20204205-sec-bypass (174961)",
                    "refsource": "XF",
                    "tags": []
                },
                {
                    "url": "https:\/\/www.ibm.com\/support\/pages\/node\/6090886",
                    "name": "https:\/\/www.ibm.com\/support\/pages\/node\/6090886",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "IBM DataPower Gateway 2018.4.1.0 through 2018.4.1.8 could allow an authenticated user to bypass security restrictions, and continue to access the server even after authentication certificates have been revolked. IBM X-Force ID: 174961."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-03-19T14:15Z",
    "lastModifiedDate": "2020-03-19T14:25Z"
}