{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-1693",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2020-1693",
                    "name": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2020-1693",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/spacewalkproject\/spacewalk\/commit\/74e28ec61d916c42061ef4347121650a1c962b0c",
                    "name": "https:\/\/github.com\/spacewalkproject\/spacewalk\/commit\/74e28ec61d916c42061ef4347121650a1c962b0c",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "A flaw was found in Spacewalk up to version 2.9 where it was vulnerable to XML internal entity attacks via the \/rpc\/api endpoint. An unauthenticated remote attacker could use this flaw to retrieve the content of certain files and trigger a denial of service, or in certain circumstances, execute arbitrary code on the Spacewalk server."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-02-17T20:15Z",
    "lastModifiedDate": "2020-02-17T20:15Z"
}