{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-5252",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/akoumjian\/python-safety-vuln",
                    "name": "https:\/\/github.com\/akoumjian\/python-safety-vuln",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/pyupio\/safety\/security\/advisories\/GHSA-7q25-qrjw-6fg2",
                    "name": "https:\/\/github.com\/pyupio\/safety\/security\/advisories\/GHSA-7q25-qrjw-6fg2",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/pyup.io\/posts\/patched-vulnerability\/",
                    "name": "https:\/\/pyup.io\/posts\/patched-vulnerability\/",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "The command-line \"safety\" package for Python has a potential security issue.\n\nThere are two Python characteristics that allow malicious code to \u00e2\u20ac\u0153poison-pill\u00e2\u20ac? command-line Safety package detection routines by disguising, or obfuscating, other malicious or non-secure packages.\n\nThis vulnerability is considered to be of low severity because the attack makes use of an existing Python condition, not the Safety tool itself.\n\nThis can happen if:\n\nYou are running Safety in a Python environment that you don\u00e2\u20ac\u2122t trust.\nYou are running Safety from the same Python environment where you have your dependencies installed.\nDependency packages are being installed arbitrarily or without proper verification.\n\nUsers can mitigate this issue by doing any of the following:\n\nPerform a static analysis by installing Docker and running the Safety Docker image: $ docker run --rm -it pyupio\/safety check -r requirements.txt\n\nRun Safety against a static dependencies list, such as the requirements.txt file, in a separate, clean Python environment.\n\nRun Safety from a Continuous Integration pipeline.\n\nUse PyUp.io, which runs Safety in a controlled environment and checks Python for dependencies without any need to install them.\n\nUse PyUp's Online Requirements Checker."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-03-23T23:15Z",
    "lastModifiedDate": "2020-03-23T23:15Z"
}